[lib]
proc-macro = true

[package]
name = "koldun_macro_derive"
version = "0.1.0"
edition = "2021"


[dependencies]
syn = { version = "2.0.28", features = ["fold", "full"] }
quote = "1.0.32"
to_snake_case = "0.1.1"
